version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE= "${DB_DATABASE}"
      - MYSQL_ROOT_PASSWORD= "${DB_PASSWORD}"
      - MYSQL_PORT= "${DB_PORT}"
    ports:
      - 3307:3306
    expose:
      - '3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
